apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
  labels:
    app: ska-oso-oet-ui
    release: test-psi-staging
  name: ska-oso-oet-ui-ingress
  namespace: ska-mid-psi-staging
spec:
  ingressClassName: nginx
  rules:
  - host: rmdskadevdu011.mda.ca
    http:
      paths:
      - backend:
          service:
            name: ska-oso-oet-ui-service
            port:
              number: 80
        path: /ska-mid-psi-staging/oet/(?!(?:[1-9[]|1[0-6[])/api)(.*)
        pathType: ImplementationSpecific
  tls:
  - hosts:
    - rmdskadevdu011.mda.ca
    secretName: ssl-cert
status:
  loadBalancer:
    ingress:
    - ip: 10.103.140.27
