apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
  labels:
    app: ska-oso-services
    release: test-psi-staging
  name: ska-oso-services-rest-test-psi-staging
  namespace: ska-mid-psi-staging
spec:
  ingressClassName: nginx
  rules:
  - host: rmdskadevdu011.mda.ca
    http:
      paths:
      - backend:
          service:
            name: ska-oso-services-rest-test-psi-staging
            port:
              number: 5000
        path: /ska-mid-psi-staging/oso/api
        pathType: Prefix
  tls:
  - hosts:
    - rmdskadevdu011.mda.ca
    secretName: ssl-cert
status:
  loadBalancer:
    ingress:
    - ip: 10.103.140.27
