apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: ska-sdp-qa-secret
  namespace: {{ .Release.Namespace }}
spec:
  type: kv-v2
  mount: kv-v2
  path: secret/sdp/qa
  destination:
    name: ska-sdp-qa-secret
    create: true
    overwrite: true