apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: ssl-cert-holder
  namespace: {{ .Release.Namespace }}
spec:
  type: kv-v2
  mount: kv-v2
  path: secret/ssl
  destination:
    name: tls-cert
    create: true
    overwrite: true